# Generated by Django 4.2.18 on 2025-03-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
