# Generated by Django 4.2.18 on 2025-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الدرس بالدقائق'),
        ),
    ]
