# Generated by Django 4.2.18 on 2025-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='مدة الدرس بالثواني (0-59)'),
        ),
    ]
