# Generated by Django 4.2.18 on 2025-04-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
    ]
