# Generated by Django 4.2.18 on 2025-04-13 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_remove_lesson_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أم خطأ')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.question')),
            ],
            options={
                'verbose_name': 'خيار سؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='مدة الاختبار بالدقائق')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='النسبة المئوية المطلوبة للنجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'اختبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrueFalseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=True, help_text="حدد إذا كانت الإجابة الصحيحة هي 'صح'")),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_answer', to='courses.question')),
            ],
            options={
                'verbose_name': 'إجابة صح/خطأ',
                'verbose_name_plural': 'إجابات صح/خطأ',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='الوقت المستغرق بالثواني')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_false_response', models.BooleanField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.questionoption')),
            ],
            options={
                'verbose_name': 'إجابة سؤال',
                'verbose_name_plural': 'إجابات الأسئلة',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
